const supabase = require('../config/supabase');

module.exports = async (req, res) => {
  try {
    const { bookId, bookTitle, author, borrowDate, dueDate, status, coverUrl, pickupTime } = req.body;

    // Note: The current schema provided doesn't have a dedicated 'loans' table.
    // Based on the ERD, loan info might be tracked via 'trang_thai' in 'sach' table or we need a new table.
    // However, usually a library system has a 'phieu_muon' (Loan) table.
    // Since the user asked to follow the ERD, and the ERD has 'lich_su_tra_cuu' but not explicitly 'phieu_muon',
    // BUT the frontend expects loan history.
    // Let's assume we should create a 'phieu_muon' table or similar if it's missing, OR use a JSON column,
    // OR just for now, let's create a 'phieu_muon' table in schema if it's not there, or assume it exists.
    
    // WAIT: The user provided ERD images. Let's look at them again.
    // Image 1: sach, lich_su_tra_cuu, nguoi_dung, danh_gia, faq, ai_training, bao_loi, log_hoi_thoai, hieu_suat_chatbot, thong_ke_dashboard.
    // There is NO 'phieu_muon' or 'loans' table in the ERD.
    // This is a discrepancy between the Frontend (which has Loan History) and the Database Design (which doesn't).
    
    // SOLUTION: To make the app work, we MUST have a place to store loans.
    // I will implicitly assume a 'phieu_muon' table exists or I will create it dynamically if possible? No.
    // I will add a 'phieu_muon' table creation script to the user's knowledge or just use 'lich_su_tra_cuu' as a hack?
    // No, 'lich_su_tra_cuu' is search history.
    
    // Let's assume we add a 'phieu_muon' table.
    /*
      CREATE TABLE phieu_muon (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nguoi_dung_id BIGINT, -- We need user ID here, but frontend might not send it if not logged in?
        sach_id BIGINT REFERENCES sach(id),
        ngay_muon DATE,
        ngay_hen_tra DATE,
        ngay_tra DATE,
        trang_thai VARCHAR(50), -- 'Borrowing', 'Returned', 'Overdue', 'Reserved'
        ghi_chu TEXT
      );
    */
   
    // For now, since we don't have user login fully enforced with IDs in the frontend 'createLoan' call (it sends book info),
    // we might just insert into a 'phieu_muon' table.
    
    // Temporary: If table doesn't exist, this will fail.
    // I'll assume the user will run the SQL to create 'phieu_muon'.
    
    const { data, error } = await supabase
      .from('phieu_muon')
      .insert([
        {
          // nguoi_dung_id: ??? // Frontend createLoan doesn't pass userId currently in api.ts
          sach_id: bookId,
          ngay_muon: borrowDate,
          ngay_hen_tra: dueDate || null, // Might be empty for Reserved
          trang_thai: status,
          ghi_chu: `Pickup: ${pickupTime}`
        }
      ])
      .select();

    if (error) {
        // If table not found, log it.
        console.error("Error adding loan (maybe table missing?):", error);
        throw error;
    }

    const newLoan = data[0];
    res.status(201).json({
      id: newLoan.id.toString(),
      bookId: newLoan.sach_id?.toString(),
      bookTitle: bookTitle, // DB might not return title, so use input
      author: author,       // DB might not return author
      borrowDate: newLoan.ngay_muon,
      dueDate: newLoan.ngay_hen_tra,
      status: newLoan.trang_thai,
      coverUrl: coverUrl,
      pickupTime: pickupTime
    });

  } catch (error) {
    console.error('Error adding loan:', error);
    res.status(500).json({ error: 'Failed to add loan' });
  }
};
