-- Add phieu_muon table to support Loan features
-- This was missing in the original ERD but is required for the App's functionality

CREATE TABLE phieu_muon (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id BIGINT REFERENCES nguoi_dung(id) ON DELETE SET NULL,
    sach_id BIGINT REFERENCES sach(id) ON DELETE SET NULL,
    ngay_muon DATE DEFAULT CURRENT_DATE,
    ngay_hen_tra DATE,
    ngay_tra DATE,
    trang_thai VARCHAR(50) DEFAULT 'Reserved', -- 'Borrowing', 'Returned', 'Overdue', 'Reserved'
    ghi_chu TEXT,
    ngay_tao TIMESTAMPTZ DEFAULT NOW()
);
