-- Database Schema for Supabase (PostgreSQL)
-- Based on the provided ER Diagram

-- Drop tables if they exist to allow re-running the script
DROP TABLE IF EXISTS thong_ke_dashboard CASCADE;
DROP TABLE IF EXISTS hieu_suat_chatbot CASCADE;
DROP TABLE IF EXISTS log_hoi_thoai CASCADE;
DROP TABLE IF EXISTS bao_loi CASCADE;
DROP TABLE IF EXISTS ai_training CASCADE;
DROP TABLE IF EXISTS faq CASCADE;
DROP TABLE IF EXISTS danh_gia CASCADE;
DROP TABLE IF EXISTS lich_su_tra_cuu CASCADE;
DROP TABLE IF EXISTS sach CASCADE;
DROP TABLE IF EXISTS nguoi_dung CASCADE;

-- 1. Table: nguoi_dung (Users)
CREATE TABLE nguoi_dung (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    so_dien_thoai VARCHAR(20),
    mat_khau_hash VARCHAR(255), -- Nullable if using OAuth later
    vai_tro VARCHAR(20) DEFAULT 'student', -- 'student', 'admin', 'librarian'
    trang_thai VARCHAR(20) DEFAULT 'active', -- 'active', 'inactive', 'banned'
    ngay_tao TIMESTAMPTZ DEFAULT NOW(),
    ngay_cap_nhat TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: sach (Books)
CREATE TABLE sach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tieu_de VARCHAR(255) NOT NULL,
    tac_gia VARCHAR(255),
    the_loai VARCHAR(100),
    mo_ta TEXT,
    nam_xuat_ban INT,
    trang_thai VARCHAR(50) DEFAULT 'Available', -- 'Available', 'Borrowed', 'Maintenance'
    anh_bia TEXT, -- Added to support book covers in UI
    ngay_tao TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: lich_su_tra_cuu (Search History)
CREATE TABLE lich_su_tra_cuu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id BIGINT REFERENCES nguoi_dung(id) ON DELETE SET NULL,
    sach_id BIGINT REFERENCES sach(id) ON DELETE CASCADE,
    thoi_gian TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: danh_gia (Reviews)
CREATE TABLE danh_gia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id BIGINT REFERENCES nguoi_dung(id) ON DELETE CASCADE,
    diem INT CHECK (diem >= 1 AND diem <= 5),
    nhan_xet TEXT,
    thoi_gian TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table: faq (Frequently Asked Questions)
CREATE TABLE faq (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cau_hoi TEXT NOT NULL,
    cau_tra_loi TEXT NOT NULL,
    ngay_tao TIMESTAMPTZ DEFAULT NOW(),
    nguoi_cap_nhat BIGINT REFERENCES nguoi_dung(id) ON DELETE SET NULL
);

-- 6. Table: ai_training (AI Training Data)
CREATE TABLE ai_training (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    du_lieu TEXT NOT NULL,
    nguoi_cap_nhat BIGINT REFERENCES nguoi_dung(id) ON DELETE SET NULL,
    thoi_gian TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Table: bao_loi (Error Reports)
CREATE TABLE bao_loi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id BIGINT REFERENCES nguoi_dung(id) ON DELETE SET NULL,
    mo_ta_loi TEXT NOT NULL,
    muc_do VARCHAR(50), -- 'Low', 'Medium', 'High', 'Critical'
    thoi_gian TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Table: log_hoi_thoai (Chat Logs)
CREATE TABLE log_hoi_thoai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nguoi_dung_id BIGINT REFERENCES nguoi_dung(id) ON DELETE SET NULL,
    cau_hoi TEXT,
    phan_hoi TEXT,
    thoi_gian TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Table: hieu_suat_chatbot (Performance Metrics)
CREATE TABLE hieu_suat_chatbot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thoi_gian TIMESTAMPTZ DEFAULT NOW(),
    do_chinh_xac FLOAT,
    do_phu_hoi FLOAT,
    so_cau_tra_loi INT
);

-- 10. Table: thong_ke_dashboard (Dashboard Stats)
CREATE TABLE thong_ke_dashboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ngay DATE,
    tong_cau_hoi INT DEFAULT 0,
    so_nguoi_dung INT DEFAULT 0,
    diem_tb FLOAT DEFAULT 0
);

-- Enable Row Level Security (RLS) - Optional but recommended
-- ALTER TABLE nguoi_dung ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE sach ENABLE ROW LEVEL SECURITY;
-- ... (Repeat for other tables if needed)
