-- Seed Books Data
INSERT INTO sach (tieu_de, tac_gia, the_loai, mo_ta, nam_xuat_ban, trang_thai, anh_bia) VALUES 
('Nhà Giả Kim', 'Paulo Coelho', 'Văn học', 'Tiểu thuyết về hành trình theo đuổi ước mơ của chàng chăn cừu Santiago.', 1988, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388211242i/69571.jpg'),
('Đắc Nhân Tâm', 'Dale Carnegie', 'Kỹ năng sống', 'Cuốn sách nổi tiếng nhất về nghệ thuật ứng xử và thu phục lòng người.', 1936, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1449557778i/4865.jpg'),
('Clean Code', 'Robert C. Martin', 'Công nghệ thông tin', 'Hướng dẫn viết mã sạch, dễ đọc và dễ bảo trì cho lập trình viên.', 2008, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1436202607i/3735293.jpg'),
('Tuổi Trẻ Đáng Giá Bao Nhiêu', 'Rosie Nguyễn', 'Kỹ năng sống', 'Cuốn sách truyền cảm hứng cho giới trẻ sống hết mình và tìm kiếm đam mê.', 2016, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1476934757i/32607050.jpg'),
('Harry Potter và Hòn Đá Phù Thủy', 'J.K. Rowling', 'Văn học', 'Tập đầu tiên trong bộ truyện Harry Potter nổi tiếng toàn cầu.', 1997, 'Borrowed', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1474154022i/3.jpg'),
('Introduction to Algorithms', 'Thomas H. Cormen', 'Công nghệ thông tin', 'Sách giáo khoa kinh điển về thuật toán và cấu trúc dữ liệu.', 2009, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1387741681i/108986.jpg'),
('Sapiens: Lược Sử Loài Người', 'Yuval Noah Harari', 'Lịch sử', 'Khám phá lịch sử tiến hóa của loài người từ thời tiền sử đến hiện đại.', 2011, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1420585954i/23692271.jpg'),
('Dế Mèn Phiêu Lưu Ký', 'Tô Hoài', 'Văn học thiếu nhi', 'Tác phẩm văn học thiếu nhi kinh điển của Việt Nam.', 1941, 'Available', 'https://upload.wikimedia.org/wikipedia/vi/8/8c/De_men_phieu_luu_ky_bia.jpg'),
('Design Patterns', 'Erich Gamma', 'Công nghệ thông tin', 'Các mẫu thiết kế phần mềm hướng đối tượng tái sử dụng.', 1994, 'Maintenance', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348027904i/85009.jpg'),
('Mắt Biếc', 'Nguyễn Nhật Ánh', 'Văn học', 'Câu chuyện tình yêu đơn phương đầy cảm động của Ngạn dành cho Hà Lan.', 1990, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1489892070i/34628867.jpg'),
('The Pragmatic Programmer', 'Andrew Hunt', 'Công nghệ thông tin', 'Những lời khuyên thực tế để trở thành một lập trình viên giỏi hơn.', 1999, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1401432508i/4099.jpg'),
('Cà Phê Cùng Tony', 'Tony Buổi Sáng', 'Kỹ năng sống', 'Những bài viết hài hước và sâu sắc về cuộc sống, công việc và khởi nghiệp.', 2015, 'Borrowed', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1442566046i/26804369.jpg'),
('Lập Trình Và Cuộc Sống', 'Jeff Atwood', 'Công nghệ thông tin', 'Tuyển tập các bài viết hay nhất từ blog Coding Horror.', 2012, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1344265551i/15792683.jpg'),
('Tắt Đèn', 'Ngô Tất Tố', 'Văn học', 'Bức tranh hiện thực về cuộc sống khốn khổ của người nông dân Việt Nam thời Pháp thuộc.', 1939, 'Available', 'https://upload.wikimedia.org/wikipedia/vi/1/1d/Tat_den.jpg'),
('JavaScript: The Good Parts', 'Douglas Crockford', 'Công nghệ thông tin', 'Khám phá những tính năng mạnh mẽ và thanh lịch nhất của JavaScript.', 2008, 'Available', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328834793i/2998152.jpg');
